Feature/#1
benauca/district-21 pull request #10
Opened 2022-09-22 13:56 UTC by jbenaventem

Include Coverage into

2022-09-22 16:07 UTC, benauca requested changes

2022-09-22 16:07 UTC, benauca commented on README.md
> +    build --> [*]
Include the coverage actions in the mermaid models

2022-09-22 16:07 UTC, benauca commented on coverage
> +mode: set
Remove this file

2022-09-23 12:24 UTC, jbenaventem commented on coverage
> +mode: set
Removed!

2022-09-23 14:28 UTC, benauca approved these changes
LGTM!!
Good Jobs ;)

2022-09-23 14:28 UTC, merged